name: waterquality
channels:
  - defaults
  - conda-forge
dependencies:
  - GDAL>=3.0.2
  - matplotlib>=3.1.2
  - PyPDF2>=1.26.0
  - scipy>=1.3.2
  - scikit-learn>=0.22
  - scikit-image>=0.16.2
  - numpy>=1.17
  - pip:
    - waterdetect>=1.5
